version: "3.9"
services:
  postgres:
    image: postgres:14.4-alpine
    container_name: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: ./env.prod
    ports:
      - 5432:5432
    networks:
      - magic_helper_network

  bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    container_name: bot
    env_file: .env.prod
    depends_on:
      - postgres
    networks:
      - magic_helper_network

networks:
  magic_helper_network:
    driver: bridge
    name: magic_helper_network

volumes:
  pg-data:

