[tool.poetry]
name = "magic-helper-vk-bot"
version = "0.1.0"
description = ""
authors = ["MaHryCT3 <mahryct123@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
vkbottle = "^4.3.10"
SQLAlchemy = "^1.4.41"
alembic = "^1.8.1"
loguru = "^0.6.0"
asyncpg = "^0.26.0"
pydantic = "^1.10.2"
aiohttp = "^3.8.3"
pendulum = "^2.1.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
python-dotenv = "^0.21.0"
black = {version = "^22.10.0", allow-prereleases = true}
flake8-return = "^1.2.0"
flake8-quotes = "^3.3.1"
isort = "^5.10.1"
flake8-isort = "^5.0.0"
flake8-pytest = "^1.4"
flake8 = "^5.0.4"
flake8-type-checking = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
multi_line_output = 3
skip_glob=[".git/*", ".venv/*", ".vscode/*", "__pycache__", "*.pyc"]
include_trailing_comma = true


[tool.black]
skip-string-normalization = true
line-length = 99
exclude = '(\.git|\.venv|\.vscode|\.env*)'