[tool.poetry]
name = "magic-helper-vk-bot"
version = "0.1.0"
description = ""
authors = ["MaHryCT3 <mahryct123@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
vkbottle = "^4.3.10"
SQLAlchemy = "^1.4.41"
alembic = "^1.8.1"
loguru = "^0.6.0"
asyncpg = "^0.26.0"
pydantic = "^1.10.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
mypy = "^0.982"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[mypy]
python_version = 3.10
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
ignore_duplicate = true
exclude = 'test*'