"""empty message

Revision ID: 3c18cc4483d4
Revises: 00efacd34169
Create Date: 2023-01-14 18:15:23.857899

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '3c18cc4483d4'
down_revision = '00efacd34169'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkdiscords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkdiscords_id'), 'checkdiscords', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkdiscords_id'), table_name='checkdiscords')
    op.drop_table('checkdiscords')
    # ### end Alembic commands ###
