"""empty message

Revision ID: 521552d24380
Revises: 6db23a3c9ae1
Create Date: 2023-01-30 11:36:26.596424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521552d24380'
down_revision = '6db23a3c9ae1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('author_nickname_report_steamid_uc', 'reports', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('author_nickname_report_steamid_uc', 'reports', ['author_nickname', 'report_steamid'])
    # ### end Alembic commands ###
