"""empty message

Revision ID: cb901c609ea2
Revises: 3c18cc4483d4
Create Date: 2023-01-26 20:32:34.088984

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = 'cb901c609ea2'
down_revision = '3c18cc4483d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('check_discord_uc', 'checkdiscords', ['check_id', 'discord_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_discord_uc', 'checkdiscords', type_='unique')
    # ### end Alembic commands ###
